-- =====================================================================
-- MCRP — Migration 07: Seed data (skills master + starter colleges)
-- Idempotent: re-running adds nothing new (conflict on case-insensitive name).
-- The skills/colleges lists are managed by admins after launch.
-- =====================================================================

insert into public.skills (name, category) values
  ('JavaScript', 'programming_language'),
  ('TypeScript', 'programming_language'),
  ('Python', 'programming_language'),
  ('Java', 'programming_language'),
  ('C', 'programming_language'),
  ('C++', 'programming_language'),
  ('C#', 'programming_language'),
  ('Go', 'programming_language'),
  ('Rust', 'programming_language'),
  ('Kotlin', 'programming_language'),
  ('Swift', 'programming_language'),
  ('PHP', 'programming_language'),
  ('Ruby', 'programming_language'),
  ('R', 'programming_language'),
  ('SQL', 'programming_language'),
  ('Dart', 'programming_language'),
  ('React', 'framework'),
  ('Next.js', 'framework'),
  ('Angular', 'framework'),
  ('Vue.js', 'framework'),
  ('Node.js', 'framework'),
  ('Express.js', 'framework'),
  ('Django', 'framework'),
  ('Flask', 'framework'),
  ('FastAPI', 'framework'),
  ('Spring Boot', 'framework'),
  ('.NET', 'framework'),
  ('Laravel', 'framework'),
  ('React Native', 'framework'),
  ('Flutter', 'framework'),
  ('Tailwind CSS', 'framework'),
  ('PostgreSQL', 'database'),
  ('MySQL', 'database'),
  ('MongoDB', 'database'),
  ('Redis', 'database'),
  ('SQLite', 'database'),
  ('Oracle', 'database'),
  ('Microsoft SQL Server', 'database'),
  ('Firebase', 'database'),
  ('Supabase', 'database'),
  ('Git', 'tool'),
  ('Docker', 'tool'),
  ('Kubernetes', 'tool'),
  ('Jenkins', 'tool'),
  ('Postman', 'tool'),
  ('Figma', 'tool'),
  ('Jira', 'tool'),
  ('Linux', 'tool'),
  ('AWS', 'cloud_platform'),
  ('Microsoft Azure', 'cloud_platform'),
  ('Google Cloud Platform', 'cloud_platform'),
  ('Vercel', 'cloud_platform'),
  ('Netlify', 'cloud_platform'),
  ('Communication', 'soft_skill'),
  ('Teamwork', 'soft_skill'),
  ('Problem Solving', 'soft_skill'),
  ('Leadership', 'soft_skill'),
  ('Time Management', 'soft_skill'),
  ('Adaptability', 'soft_skill'),
  ('Critical Thinking', 'soft_skill')
on conflict (lower(name)) do nothing;

insert into public.colleges (name, city, state, is_approved) values
  ('R.V. College of Engineering', 'Bengaluru', 'Karnataka', true),
  ('BMS College of Engineering', 'Bengaluru', 'Karnataka', true),
  ('PES University', 'Bengaluru', 'Karnataka', true),
  ('M S Ramaiah Institute of Technology', 'Bengaluru', 'Karnataka', true),
  ('Dayananda Sagar College of Engineering', 'Bengaluru', 'Karnataka', true),
  ('BMS Institute of Technology and Management', 'Bengaluru', 'Karnataka', true),
  ('Bangalore Institute of Technology', 'Bengaluru', 'Karnataka', true),
  ('Visvesvaraya Technological University', 'Belagavi', 'Karnataka', true),
  ('National Institute of Technology Karnataka', 'Surathkal', 'Karnataka', true),
  ('Indian Institute of Science', 'Bengaluru', 'Karnataka', true)
on conflict (lower(name)) do nothing;
